# docker-composeのバージョン
version: "3"
services:
  dataly_build_local_dev:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dataly_build_local_dev
    volumes:
      - ../../:/app
    command: sh -c "
      npm i -f &&
      npm run test &&
      npm run build_local_dev"