steps:
  ###########################################################
  # Step 1: npm install , test and build
  ###########################################################
  - name: 'gcr.io/cloud-builders/npm'
    id: npm-install
    args: 
      - i
      - -f
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/npm'
    id: npm-test
    args: ['run','test']
    waitFor: ['npm-install']
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_build_dev
    args: ['run','build_dev']
    # waitFor: ['npm-test']
  ###########################################################
  # Step 2: gcloud copy step
  ###########################################################
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'cp-dataly.js'
    args: ['cp', 'public/js/dataly/dataly.min.js', 'gs://dev_script.atdataly.jp/script/dataly.min.js']
    waitFor: ['npm_build_dev']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'cp-dataly.js.map'
    args: ['cp', 'public/js/dataly/dataly.min.js.map', 'gs://dev_script.atdataly.jp/script/dataly.min.js.map']
    waitFor: ['npm_build_dev']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'cp-atimplementor.min.js'
    args: ['cp', 'public/js/implementor/atimplementor.min.js', 'gs://dev_script.atdataly.jp/script/atimplementor.min.js']
    waitFor: ['npm_build_dev']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'cp-atimplementor.min.js.map'
    args: ['cp', 'public/js/implementor/atimplementor.min.js.map', 'gs://dev_script.atdataly.jp/script/atimplementor.min.js.map']
    waitFor: ['npm_build_dev']
  ###########################################################
  # Step 3: gcloud cmod step
  ###########################################################
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'acl-atimplementor.min.js'
    args:
      - acl
      - ch
      - -u
      - AllUsers:R
      - gs://dev_script.atdataly.jp/script/atimplementor.min.js
    waitFor: ['cp-dataly.js']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'acl-atimplementor.min.js.map'
    args:
      - acl
      - ch
      - -u
      - AllUsers:R
      - gs://dev_script.atdataly.jp/script/atimplementor.min.js.map
    waitFor: ['cp-dataly.js.map']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'acl-dataly.min.js'
    args:
      - acl
      - ch
      - -u
      - AllUsers:R
      - gs://dev_script.atdataly.jp/script/dataly.min.js
    waitFor: ['cp-atimplementor.min.js']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'acl-dataly.min.js.map'
    args:
      - acl
      - ch
      - -u
      - AllUsers:R
      - gs://dev_script.atdataly.jp/script/dataly.min.js.map
    waitFor: ['cp-atimplementor.min.js.map']
  ##########################################################
  # Step 3: gcloud copy step html and acl html
  ##########################################################
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'site1'
    args: ['cp', 'public/html/dev/gcp/site1/*.html', 'gs://dev_script.atdataly.jp/static/site1']
    waitFor: ['npm_build_dev']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'site2'
    args: ['cp', 'public/html/dev/gcp/site2/*.html', 'gs://dev_script.atdataly.jp/static/site2']
    waitFor: ['npm_build_dev']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'site3'
    args: ['cp', 'public/html/dev/gcp/site3/*.html', 'gs://dev_script.atdataly.jp/static/site3']
    waitFor: ['npm_build_dev']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'acl-site1'
    args:
      - acl
      - ch
      - -u
      - AllUsers:R
      - -r
      - gs://dev_script.atdataly.jp/static/site1/
    waitFor: ['site1']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'acl-site2'
    args:
      - acl
      - ch
      - -u
      - AllUsers:R
      - -r
      - gs://dev_script.atdataly.jp/static/site2/
    waitFor: ['site2']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'acl-site3'
    args:
      - acl
      - ch
      - -u
      - AllUsers:R
      - -r
      - gs://dev_script.atdataly.jp/static/site3/
    waitFor: ['site3']